name: auto build
on:
  workflow_dispatch:
    branches:
      - main
      - fast
  push:
    branches:
      - main
      - fast
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows x86_64
            os: windows-2022
            msvc_arch: x64
          - name: Ubuntu
            os: ubuntu-latest
          - name: Mac ARM64
            os: macos-latest
            osx_arch: arm64
    env:
      CC: clang
      CXX: clang++
      CMAKE_GENERATOR: Ninja
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/setup-nasm@v1
      - name: Ubuntu / Mac
        if: ${{ !contains( matrix.config.os, 'windows' ) }}
        run: >
          cmake --fresh -B svt_build -DCMAKE_BUILD_TYPE=Release
          -DBUILD_SHARED_LIBS=OFF -DSVT_AV1_LTO=ON -DENABLE_AVX512=ON
          -DCMAKE_OSX_ARCHITECTURES=${{ matrix.config.osx_arch }}
          -DNATIVE=ON
          -DREPRODUCIBLE_BUILDS=ON
        shell: bash
      - name: Windows
        if: contains( matrix.config.os, 'windows' )
        run: >
          cmake --fresh -B svt_build -DCMAKE_BUILD_TYPE=Release
          -DBUILD_SHARED_LIBS=OFF -DSVT_AV1_LTO=OFF -DENABLE_AVX512=ON
          -DCMAKE_C_FLAGS_RELEASE="-O3 -DNDEBUG -march=x86-64-v4 -flto"
          -DCMAKE_CXX_FLAGS_RELEASE="-O3 -DNDEBUG -march=x86-64-v4 -flto"
          -DREPRODUCIBLE_BUILDS=ON
          -DCMAKE_EXE_LINKER_FLAGS="-flto"
        shell: cmd
      - name: Build
        run: |
          cmake --build svt_build --config Release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.name }}
          path: Bin/Release/
          retention-days: 90
      - name: Delete existing release
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete ${{ matrix.config.os }} --cleanup-tag
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ matrix.config.os }}_fast
          name: Release ${{ matrix.config.name }}
          draft: false
          prerelease: false
          body: ${{ matrix.config.os }} auto build
          files: |
            Bin/Release/*
